### ISSUE TITLE
Question? AM TX  is possible?

### ISSUE THREAD

**Issue by kinetikFR** [whosmatt/uvmod#18]
i would like know  it is possible AM TX on Aviation range

**Comment by whosmatt** [comment]
possible yes, already implemented too but HIGHLY dangerous and illegal if youre planning to transmit without a dummy load.

**Comment by kinetikFR** [comment]
How do I proceed, it would only be for study purposes I recently bought a hackrf and was testing it

**Comment by whosmatt** [comment]
Which attenuator are you using?

**Comment by whosmatt** [comment]
Besides, for AM TX you need to modify the hardware of the radio, you would need to inject baseband into the pa to modulate it. And please remember that transmitting on airband is not just very illegal, most countries do have a lost aircraft detection system, so they get an alert with your approximate location if you do.
