### ISSUE TITLE
 Custom TX Range upper limit too strict

### ISSUE THREAD

**Issue by mike-van-e** [whosmatt/uvmod#19]
When I enable the hidden features of UVMOD, i check the box for Custom TX Range.

I then define the following lower limit:

446006250

And the following upper limit:

446193750

These are the official PMR frequencies.

But now, when going to 446.193750 and I press the PTT button, I get the message "disabled" even though that's the upper limit define by me, the lower limit (446.006250) works fine, and I'm able to transmit on it.

It looks to me like the compare of the current frequency and the lower/upper limit is a bit broken.

Is looks like it's making a >= compare instead of a > compare. (I'm not sure how it's technically implemented)

**Comment by whosmatt** [comment]
well, thats exactly what it is. its not that easy to change the actual comparison since i manually edited the bytecode and adding an instruction would require rereferencing all the following instructions. 
ill just push a change where the javascript increments the upper limit before packing it
