### ISSUE TITLE
Dodatkowe kroki strojenia i podmiana kanałów NOAA

### ISSUE THREAD

**Issue by Pomidor78** [whosmatt/uvmod#2]
1. Można dodać dodatkowe kroki strojenia https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/8010093e09cecaf918252cc011f08058d7f9370d/uvmod_kitchen/mod_more_freq_steps_and_backlight_duration.py  (dzięki czemu czas podświetlenia może być przedłużony do 10 sekund) - sprawdziłem, działa razem z tym modem.
2. Podmiana kanałów NOAA na inne https://github.com/amnemonic/Quansheng_UV-K5_Firmware/blob/8010093e09cecaf918252cc011f08058d7f9370d/uvmod_kitchen/mod_custom_noaa_freqs.py  (ja wpisuję tam kanały FM link bo tylko te wg. mnie nadają się do słuchania z otwartym SQ) - sprawdziłem, działa razem z tym modem.
A jakby ustawić częstotliwość roger beep na 1050 Hz to będzie można nim odblokować odbiór na kanałach NOAA ?

I jeszcze raz wielkie dzięki za UVMOD, chciałem coś takiego zrobić w Python ale ten online jest o wiele lepszy!
![UV-K5 NOAA zmienione](https://github.com/whosmatt/uvmod/assets/141545846/750dd7f0-9f66-436a-a627-a2d023dc6626)

**Comment by whosmatt** [comment]
Additional tuning steps is currently broken because of an overloaded variable. Besides backlight, other menu variables also go higher, and they can crash the radio. Use the "Double backlight duration" mod instead. 

I will add the NOAA frequencies mod soon. 

Please do not transmit on NOAA emergency broadcast channels.

**Comment by Pomidor78** [comment]
Sprawdziłem, ustawiając roger beep na 1050 Hz da się otwierać kanały PMR wpisane zamiast kanałów NOAA
![UV-K5 PMR_to_NOAA](https://github.com/whosmatt/uvmod/assets/141545846/5f31fb37-494d-4fdd-aa3d-3dd34431a045)
![Zrzut ekranu (312)](https://github.com/whosmatt/uvmod/assets/141545846/fa04599a-0df4-4443-bb76-f7b2b1ababfe)
