### ISSUE TITLE
Air band transmit

### ISSUE THREAD

**Issue by OneOfEleven** [whosmatt/uvmod#22]
Hi

The air band actually goes from 108MHz to 136MHz rather than 118MHz to 136MHz.

The lower half (108MHz to 118MHz) is used for ILS (instrument landing system) and VOR (VHF OmniRange) .. ie, used at and around the run way strips.

So really it'd be best to extend you air band TX disable to go from 108MHz to 136MHz. Anyone caught transmitting on the lower half to try and block their landing systems would soon be found and dealt with (as they would be on the upper comms half).

**Comment by whosmatt** [comment]
thanks for the tip, i changed it and it will go online with the major upcoming update. I decided to remove the tx everywhere but air band mod since its redundant and changed the default value of the custom tx range mod to your suggested values.
