### ISSUE TITLE
UVMOD with AM fix custom release v0.16

### ISSUE THREAD

**Issue by sbright33** [whosmatt/uvmod#27]
I'd like to use both together? Which of your features are missing from v0.16? TX everywhere is the first I noticed. Now I can't transmit. How can I achieve this? Will you have a new release soon?

AM fix is important to me.

I remember being able to transmit AM in the airband. Was that a different radio?

https://github.com/egzumer/uv-k5-firmware-custom/releases

Your Mod is wonderful thank you!
Steve

**Comment by whosmatt** [comment]
This radio is not capable of transmitting AM. Nor should you in any scenario transmit on airband without approved hardware. 
The custom firmware is oefw based and not supported yet. The dev branch has initial oefw support but no mods and transferring the mods is beyond my scope at the moment.
