### ISSUE TITLE
WebSerial is not supported in Brave browser

### ISSUE THREAD

**Issue by dbellomo** [whosmatt/uvmod#28]
"WebSerial is not supported in this browser. Use a chromium based browser such as Chrome, Edge, Opera..."

Brave browser is a chromium based browser and don't work on it.

**Comment by whosmatt** [comment]
Thats a brave issue. They seem to have disabled it by default and it may or
may not be possible to reenable it.

**Comment by dbellomo** [comment]
ok. Is a Brave issue.
Regards.
