### ISSUE TITLE
Backlight stays lit when scanning through memory channels or frequency

### ISSUE THREAD

**Issue by lyczewskiand** [whosmatt/uvmod#30]
Used website https://whosmatt.github.io/uvmod/ to compile and write firmware to my UV-K5 and backlight stays lit when scanning through memory channels or frequency. Unfortunately I do not remember exact options I chose but for sure:
- Apps: RSSI, S-Meter and battery voltage readout on the main screen. By @piotr022, v78.
- Battery icon: Changes the battery icon to a more normal looking variant.
- Increase Mic Gain: Gives the microphone gain an additional boost, making the microphone generally more sensitive.
- NOAA Frequencies
- Custom Frequency Ranges: Simple Mode: Extend Band 1 down to 18 MHz and Band 7 up to 1300 MHz. This is the maximum frequency range of the chip.

**Comment by whosmatt** [comment]
this is just a bug in the v26 and v27 firmware unrelated to uvmod
